name: Analyze
on:
  push:
    paths:
    - 'vpc/**'
    branches:
      - main
  pull_request:
    paths:
      - 'vpc/**'

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test
        run: |
          ls -al
          pwd